CREATE TABLE `alerts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`alertType` enum('new_appointment','cancellation','urgent_message','reminder','system','lead_hot','follow_up') NOT NULL,
	`title` varchar(255) NOT NULL,
	`alertMessage` text,
	`isRead` boolean NOT NULL DEFAULT false,
	`relatedId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `alerts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `anamnesis` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`patientId` int NOT NULL,
	`mainComplaint` text,
	`symptomOnset` varchar(255),
	`symptomDuration` varchar(128),
	`triggeringFactors` text,
	`previousTreatments` text,
	`currentMedications` text,
	`psychiatristName` varchar(255),
	`personalHistory` text,
	`childhoodHistory` text,
	`adolescenceHistory` text,
	`significantTraumas` text,
	`familyHistory` text,
	`familyMentalHealth` text,
	`familyRelationships` text,
	`maritalStatus` varchar(64),
	`occupation` varchar(255),
	`educationLevel` varchar(128),
	`livingArrangement` text,
	`socialNetwork` text,
	`leisureActivities` text,
	`sleepPattern` text,
	`eatingPattern` text,
	`substanceUse` text,
	`mentalStatusExam` text,
	`clinicalImpression` text,
	`diagnosticHypothesis` text,
	`riskAssessment` text,
	`additionalNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `anamnesis_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `appointments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`patientId` int,
	`title` varchar(255) NOT NULL,
	`description` text,
	`startTime` bigint NOT NULL,
	`endTime` bigint NOT NULL,
	`apptStatus` enum('scheduled','confirmed','completed','cancelled','no_show') NOT NULL DEFAULT 'scheduled',
	`googleEventId` varchar(255),
	`apptSource` enum('manual','whatsapp','telegram','instagram','google_calendar','website') NOT NULL DEFAULT 'manual',
	`reminderSent` boolean NOT NULL DEFAULT false,
	`icsSent` boolean NOT NULL DEFAULT false,
	`bookingName` varchar(255),
	`bookingEmail` varchar(320),
	`bookingPhone` varchar(32),
	`bookingMessage` text,
	`leadId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `appointments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cognitiveConcepts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`patientId` int NOT NULL,
	`coreBeliefsAboutSelf` text,
	`coreBeliefsAboutOthers` text,
	`coreBeliefsAboutWorld` text,
	`intermediateBeliefsRules` text,
	`intermediateBeliefsAttitudes` text,
	`intermediateBeliefsAssumptions` text,
	`compensatoryStrategies` text,
	`cognitiveDistortions` json,
	`mainAutomaticThoughts` text,
	`behavioralPatterns` text,
	`emotionalPatterns` text,
	`precipitatingFactors` text,
	`perpetuatingFactors` text,
	`protectiveFactors` text,
	`caseFormulationSummary` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cognitiveConcepts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`patientId` int NOT NULL,
	`fileName` varchar(255) NOT NULL,
	`fileKey` varchar(512) NOT NULL,
	`fileUrl` text NOT NULL,
	`mimeType` varchar(128),
	`fileSize` int,
	`docCategory` enum('evolution','report','exam','prescription','other') NOT NULL DEFAULT 'other',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `gestaltAssessments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`patientId` int NOT NULL,
	`assessmentDate` timestamp NOT NULL DEFAULT (now()),
	`preContact` text,
	`contact` text,
	`finalContact` text,
	`postContact` text,
	`confluence` int NOT NULL DEFAULT 0,
	`introjection` int NOT NULL DEFAULT 0,
	`projection` int NOT NULL DEFAULT 0,
	`retroflection` int NOT NULL DEFAULT 0,
	`deflection` int NOT NULL DEFAULT 0,
	`egotism` int NOT NULL DEFAULT 0,
	`bodyAwareness` text,
	`emotionalAwareness` text,
	`cognitiveAwareness` text,
	`emergentNeeds` text,
	`unfinishedGestalten` text,
	`relationalField` text,
	`experiments` json,
	`clinicalNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `gestaltAssessments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `integrationSettings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`intProvider` enum('google_calendar','whatsapp','telegram','instagram') NOT NULL,
	`intConfig` json,
	`isActive` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `integrationSettings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `inventoryResults` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`patientId` int NOT NULL,
	`inventoryType` enum('BDI_II','BAI','YSQ_S3','PHQ9','GAD7','WHOQOL','CUSTOM') NOT NULL,
	`inventoryName` varchar(255) NOT NULL,
	`applicationDate` timestamp NOT NULL DEFAULT (now()),
	`totalScore` int,
	`maxScore` int,
	`classification` varchar(128),
	`subscaleScores` json,
	`itemResponses` json,
	`interpretation` text,
	`clinicalNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `inventoryResults_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `leadInteractions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`leadId` int NOT NULL,
	`interactionChannel` enum('whatsapp','telegram','instagram','website','telefone','email') NOT NULL,
	`interactionType` enum('mensagem_recebida','mensagem_enviada','comentario','dm','visita_site','agendamento','cancelamento','follow_up','ligacao') NOT NULL,
	`content` text,
	`metadata` json,
	`scoreImpact` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `leadInteractions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255),
	`phone` varchar(32),
	`email` varchar(320),
	`instagramHandle` varchar(128),
	`telegramChatId` varchar(64),
	`leadSource` enum('whatsapp','telegram','instagram','website','indicacao','outro') NOT NULL,
	`sourceDetail` varchar(255),
	`funnelStage` enum('lead','contato','interesse','agendamento','consulta','paciente_ativo','perdido') NOT NULL DEFAULT 'lead',
	`score` int NOT NULL DEFAULT 0,
	`interactionCount` int NOT NULL DEFAULT 1,
	`lastInteractionAt` timestamp NOT NULL DEFAULT (now()),
	`firstInteractionAt` timestamp NOT NULL DEFAULT (now()),
	`convertedToPatientId` int,
	`convertedAt` timestamp,
	`appointmentId` int,
	`nextFollowUpAt` timestamp,
	`followUpCount` int NOT NULL DEFAULT 0,
	`lastFollowUpAt` timestamp,
	`notes` text,
	`tags` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `messageLog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`patientId` int,
	`leadId` int,
	`msgChannel` enum('whatsapp','telegram','instagram') NOT NULL,
	`msgDirection` enum('inbound','outbound') NOT NULL,
	`content` text,
	`messageId` varchar(255),
	`senderName` varchar(255),
	`senderHandle` varchar(255),
	`msgStatus` varchar(32),
	`msgMetadata` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `messageLog_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `moodEntries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`patientId` int NOT NULL,
	`appointmentId` int,
	`mood` int NOT NULL,
	`moodLabel` varchar(64),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `moodEntries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `patients` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`email` varchar(320),
	`phone` varchar(32),
	`whatsappId` varchar(64),
	`telegramChatId` varchar(64),
	`instagramHandle` varchar(128),
	`dateOfBirth` varchar(10),
	`notes` text,
	`patientSource` enum('whatsapp','telegram','instagram','website','indicacao','manual') NOT NULL DEFAULT 'manual',
	`patientSourceDetail` varchar(255),
	`leadId` int,
	`primaryApproach` enum('tcc','terapia_esquema','gestalt','integrativa') NOT NULL DEFAULT 'integrativa',
	`patientStatus` enum('active','inactive','archived') NOT NULL DEFAULT 'active',
	`sessionStreak` int NOT NULL DEFAULT 0,
	`totalSessions` int NOT NULL DEFAULT 0,
	`badges` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `patients_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `professionalProfile` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`displayName` varchar(255) NOT NULL DEFAULT 'Psi. Daniela Coelho',
	`title` varchar(255) NOT NULL DEFAULT 'Psicóloga Clínica',
	`subtitle` varchar(512),
	`bio` text,
	`crp` varchar(32),
	`specialties` json,
	`education` json,
	`photoUrl` text,
	`heroPhotoUrl` text,
	`instagramUrl` varchar(512),
	`instagramHandle` varchar(128),
	`tiktokUrl` varchar(512),
	`tiktokHandle` varchar(128),
	`youtubeUrl` varchar(512),
	`youtubeHandle` varchar(128),
	`whatsappNumber` varchar(32),
	`telegramUrl` varchar(512),
	`linkedinUrl` varchar(512),
	`websiteUrl` varchar(512),
	`profileEmail` varchar(320),
	`profilePhone` varchar(32),
	`address` text,
	`city` varchar(128),
	`state` varchar(64),
	`primaryColor` varchar(32),
	`accentColor` varchar(32),
	`tagline` varchar(512),
	`yearsExperience` int,
	`patientsServed` int,
	`sessionsCompleted` int,
	`featuredVideoUrl` text,
	`featuredReelUrls` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `professionalProfile_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `schemaAssessments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`patientId` int NOT NULL,
	`assessmentDate` timestamp NOT NULL DEFAULT (now()),
	`abandonment` int NOT NULL DEFAULT 0,
	`mistrust` int NOT NULL DEFAULT 0,
	`emotionalDeprivation` int NOT NULL DEFAULT 0,
	`defectiveness` int NOT NULL DEFAULT 0,
	`socialIsolation` int NOT NULL DEFAULT 0,
	`dependence` int NOT NULL DEFAULT 0,
	`vulnerability` int NOT NULL DEFAULT 0,
	`enmeshment` int NOT NULL DEFAULT 0,
	`failure` int NOT NULL DEFAULT 0,
	`entitlement` int NOT NULL DEFAULT 0,
	`insufficientSelfControl` int NOT NULL DEFAULT 0,
	`subjugation` int NOT NULL DEFAULT 0,
	`selfSacrifice` int NOT NULL DEFAULT 0,
	`approvalSeeking` int NOT NULL DEFAULT 0,
	`negativity` int NOT NULL DEFAULT 0,
	`emotionalInhibition` int NOT NULL DEFAULT 0,
	`unrelentingStandards` int NOT NULL DEFAULT 0,
	`punitiveness` int NOT NULL DEFAULT 0,
	`schemaModes` json,
	`copingStyles` json,
	`clinicalNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `schemaAssessments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sessionEvolutions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`patientId` int NOT NULL,
	`appointmentId` int,
	`sessionNumber` int NOT NULL DEFAULT 1,
	`sessionDate` timestamp NOT NULL DEFAULT (now()),
	`patientPresentation` text,
	`moodAtArrival` int,
	`moodAtDeparture` int,
	`mainThemes` json,
	`activatedSchemas` json,
	`identifiedThoughts` text,
	`identifiedEmotions` text,
	`identifiedBehaviors` text,
	`techniquesUsed` json,
	`interventionsSummary` text,
	`homeworkAssigned` text,
	`previousHomeworkReview` text,
	`homeworkCompleted` boolean DEFAULT false,
	`progressNotes` text,
	`riskLevel` enum('none','low','moderate','high','critical') NOT NULL DEFAULT 'none',
	`riskNotes` text,
	`nextSessionPlan` text,
	`goalsProgress` json,
	`transcription` text,
	`aiSummary` text,
	`aiSuggestions` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sessionEvolutions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sessionNotes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`patientId` int NOT NULL,
	`appointmentId` int,
	`content` text NOT NULL,
	`summary` text,
	`transcription` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sessionNotes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `testimonials` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`authorName` varchar(255) NOT NULL,
	`authorInitials` varchar(8),
	`content` text NOT NULL,
	`rating` int NOT NULL DEFAULT 5,
	`isPublished` boolean NOT NULL DEFAULT true,
	`sortOrder` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `testimonials_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `thoughtRecords` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`patientId` int NOT NULL,
	`sessionNoteId` int,
	`recordDate` timestamp NOT NULL DEFAULT (now()),
	`situation` text,
	`automaticThought` text,
	`emotions` json,
	`evidenceFor` text,
	`evidenceAgainst` text,
	`alternativeThought` text,
	`emotionsAfter` json,
	`cognitiveDistortion` varchar(128),
	`behavioralExperiment` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `thoughtRecords_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `treatmentPlans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`patientId` int NOT NULL,
	`approach` varchar(128) NOT NULL DEFAULT 'Integrativa (TCC + TE + Gestalt)',
	`sessionFrequency` varchar(64),
	`estimatedDuration` varchar(128),
	`mainObjectives` json,
	`therapeuticStrategies` json,
	`goals` json,
	`plannedTechniques` json,
	`dischargeCriteria` text,
	`observations` text,
	`planStatus` enum('active','completed','suspended') NOT NULL DEFAULT 'active',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `treatmentPlans_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` int AUTO_INCREMENT NOT NULL,
	`openId` varchar(64) NOT NULL,
	`name` text,
	`email` varchar(320),
	`loginMethod` varchar(64),
	`role` enum('user','admin') NOT NULL DEFAULT 'user',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lastSignedIn` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_openId_unique` UNIQUE(`openId`)
);
