CREATE TABLE `instagramAISuggestions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`suggestionType` enum('caption','hashtags','content_idea','posting_time','audience_targeting','growth_strategy') NOT NULL,
	`content` text,
	`reasoning` text,
	`expectedImpact` varchar(128),
	`isApplied` boolean NOT NULL DEFAULT false,
	`appliedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `instagramAISuggestions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `instagramAnalytics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`followers` int NOT NULL DEFAULT 0,
	`followersGrowth` int NOT NULL DEFAULT 0,
	`followersGrowthRate` decimal(5,2) DEFAULT '0.00',
	`totalEngagement` int NOT NULL DEFAULT 0,
	`avgEngagementRate` decimal(5,2) DEFAULT '0.00',
	`avgLikesPerPost` decimal(8,2) DEFAULT '0.00',
	`avgCommentsPerPost` decimal(8,2) DEFAULT '0.00',
	`totalReach` int NOT NULL DEFAULT 0,
	`totalImpressions` int NOT NULL DEFAULT 0,
	`avgReachPerPost` int NOT NULL DEFAULT 0,
	`audienceDemographics` json,
	`topAudienceCountries` json,
	`topAudienceCities` json,
	`bestPerformingContentType` varchar(128),
	`bestPerformingTheme` varchar(128),
	`bestTimeToPost` varchar(32),
	`bestDayToPost` varchar(32),
	`estimatedMonthlyEarnings` decimal(10,2) DEFAULT '0.00',
	`reelsPlayCount` int NOT NULL DEFAULT 0,
	`reelsEarnings` decimal(10,2) DEFAULT '0.00',
	`growthScore` int NOT NULL DEFAULT 0,
	`recommendations` json,
	`analyticsPeriod` enum('daily','weekly','monthly') NOT NULL DEFAULT 'daily',
	`periodDate` date NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `instagramAnalytics_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `instagramContentCalendar` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`month` int NOT NULL,
	`year` int NOT NULL,
	`theme` varchar(255),
	`strategy` text,
	`goals` json,
	`contentIdeas` json,
	`hashtags` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `instagramContentCalendar_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `instagramPosts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`instagramPostId` varchar(255),
	`caption` text,
	`content` text,
	`mediaUrls` json,
	`mediaType` enum('image','video','carousel','reel','story') NOT NULL,
	`hashtags` text,
	`mentions` text,
	`callToAction` varchar(255),
	`scheduledFor` timestamp,
	`publishedAt` timestamp,
	`postStatus` enum('draft','scheduled','published','archived') NOT NULL DEFAULT 'draft',
	`views` int NOT NULL DEFAULT 0,
	`likes` int NOT NULL DEFAULT 0,
	`comments` int NOT NULL DEFAULT 0,
	`shares` int NOT NULL DEFAULT 0,
	`saves` int NOT NULL DEFAULT 0,
	`reach` int NOT NULL DEFAULT 0,
	`impressions` int NOT NULL DEFAULT 0,
	`engagementRate` decimal(5,2) DEFAULT '0.00',
	`aiOptimizationScore` int,
	`aiSuggestions` json,
	`bestTimeToPost` varchar(32),
	`targetAudience` json,
	`theme` varchar(128),
	`contentType` enum('educational','testimonial','promotional','behind_the_scenes','interactive','motivational') NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `instagramPosts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `instagramReels` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`instagramReelId` varchar(255),
	`videoUrl` text,
	`thumbnail` text,
	`caption` text,
	`hashtags` text,
	`music` varchar(255),
	`duration` int,
	`scheduledFor` timestamp,
	`publishedAt` timestamp,
	`reelStatus` enum('draft','scheduled','published','archived') NOT NULL DEFAULT 'draft',
	`views` int NOT NULL DEFAULT 0,
	`likes` int NOT NULL DEFAULT 0,
	`comments` int NOT NULL DEFAULT 0,
	`shares` int NOT NULL DEFAULT 0,
	`saves` int NOT NULL DEFAULT 0,
	`reach` int NOT NULL DEFAULT 0,
	`engagementRate` decimal(5,2) DEFAULT '0.00',
	`aiOptimizationScore` int,
	`aiSuggestions` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `instagramReels_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `instagramStories` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`instagramStoryId` varchar(255),
	`mediaUrl` text,
	`storyMediaType` enum('image','video') NOT NULL,
	`text` text,
	`stickers` json,
	`scheduledFor` timestamp,
	`publishedAt` timestamp,
	`storyStatus` enum('draft','scheduled','published','archived') NOT NULL DEFAULT 'draft',
	`views` int NOT NULL DEFAULT 0,
	`replies` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `instagramStories_id` PRIMARY KEY(`id`)
);
